#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 31 22:24:11 2018

@author: apb
"""

import tensorflow as tf
X=tf.constant([6])
Y=tf.constant([9])

result=tf.multiply(X,Y)

with tf.Session() as sess:
    print(sess.run(result))